name: Image Compression

on:
  push:
    branches:
      - master

jobs:
  compress-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install squoosh-cli
        run: npm install -g @squoosh/cli

      - name: Compress images
        run: |
          find . -path "*/images/*.jpg" \
            -not -name "*-compressed.jpg" \
            -not -name "*-compressed.webp" \
            -exec bash -c ' \
              squoosh-cli --max-optimizer-rounds 6 --mozjpeg --webp \
                -d "$(dirname "{}")" -s "-compressed" "{}" && \
              echo "Compressed {}"' \;
